trigger:
- master

#pool:
#  vmImage: 'ubuntu-latest'
pool:
  name: Local Agent

variables:
  OPENSHIFT_URL: 'https://api.rm2.thpm.p1.openshiftapps.com:6443'   # Reemplaza con tu URL real
  OPENSHIFT_TOKEN: 'sha256~u_njHpCey1gVAe1e-dkBb1af7bRIar16h4WS6F_d7rY'          # Configura como variable secreta
  OPENSHIFT_NAMESPACE: 'jcalvo-dev'                 # Cambia si usas otro namespace

steps:

# Login a OpenShift
- script: |
    oc login $(OPENSHIFT_URL) --token=$(OPENSHIFT_TOKEN) --insecure-skip-tls-verify
    oc project $(OPENSHIFT_NAMESPACE)
  displayName: 'Login en OpenShift'

# Crear nueva app desde GitHub
- script: |
    oc new-app https://github.com/rcarneironet/nodejs-ex -l name=vssummit-app
  displayName: 'Crear nueva app en OpenShift'

# Iniciar build manual
- script: |
    oc start-build nodejs-ex --follow
  displayName: 'Iniciar build'

# Ver estado de la app
- script: |
    oc status
  displayName: 'Ver estado del despliegue'
